### ISSUE TITLE
wifi mac address always changed after reboot

### ISSUE THREAD

**Issue by jhonoryza** [aib/opi2g-utils#3]
is it a bug ??

**Comment by aib** [comment]
Hmm, I had not noticed.
I know the Wi-Fi performance is appalling, though. Any nice fixes there?

**Comment by jhonoryza** [comment]
@txurtxil told me that u-boot form xunlong can correct this issue https://github.com/OrangePiLibra/OrangePiRDA_uboot

can u update your u-boot sources to fix this problem? :)

**Comment by txurtxil** [comment]
Mio error, I think I was confused. I prepared an image of ubuntu that supposedly has the corrected MAC rotate, but I made it with the uboot
  https://github.com/RDA8810/u-boot-RDA8810

The image of ubuntu is this:
http://surfero.blogspot.com.es/2017/06/distribucion-gnulinux-para-orange-pi-2g.html

**Comment by jhonoryza** [comment]
so that ubuntu image has the fix corrected mac address??is that right?

**Comment by txurtxil** [comment]
Can you try it? right now I can not assure you

**Comment by jhonoryza** [comment]
ok i'll try it...

**Comment by jhonoryza** [comment]
i have try it, and mac address still always changed after reboot..
i think there is a bug in wifi driver

**Comment by GMMan** [comment]
The reason the MAC address keeps on changing is you're missing the NVRAM (`factorydata`) partition. Add in a 2MB `factorydata` partition to your `mtdparts`, reflash, and after the system boots, reboot and a randomly generated MAC address will be written into the NVRAM partition (important that you reboot, because the NVRAM is only written in U-Boot), which the WiFi driver can retrieve in subsequent boots. For SD card installations, shrink the rootfs and add a 2MB partition at the end, and make sure to set the GPT partition name to `factorydata` so U-Boot can find it.

There's also a prdinfo partition (`misc`), but it's not too important.

**Comment by hoopertsau** [comment]
I have tried another way to fix it.
1. undefine  USE_MAC_FROM_RDA_NVRAM
    OrangePiRDA/kernel/drivers/net/wireless/rdaw80211/rdawlan/wland_defs.h
    line 194
    comment the line  "#define USE_MAC_FROM_RDA_NVRAM"
    rebuild the kernel
2. Write mac addr to file at /data/misc/wifi/WLANMAC on sdcard
    The driver read the first 6 bytes for mac addr.

**Comment by hoopertsau** [comment]
https://wiki.pbeirne.com/patb/i96/wiki/Useful_Info
