### ISSUE TITLE
UBIfs data loss

### ISSUE THREAD

**Issue by netomx** [aib/opi2g-utils#5]
Powering down and up, I noticed it has data loss. So maybe we need to mount ubifs with sync to prevent it? Will test it today

mount -o remount,rw,sync /

**Comment by aib** [comment]
The shutdown script should take care of unmounting / cleanly.

But, ah, / should be mounted read-only, anyway. I will update my article.

**Comment by netomx** [comment]
But how about a power loss?

And if you mount it read-only, what about the (user) files?

**Comment by aib** [comment]
Ah, I see your point.

Well, the mount(8) manual page specifically warns against using `sync` because it shortens the storage's lifespan. While we would need to do testing to be sure, it sounds like a bad idea to disable write combining without analyzing and/or modifying the number, frequency and size of writes to the disk.

(I have also changed my mind about the read-only mount by default. The article should simply stick to the defaults, readers are free to change them, anyway.)
